# Generated by Django 4.0.5 on 2022-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('date', models.DateField(unique=True)),
                ('time', models.TimeField(unique=True)),
                ('mobile', models.IntegerField(max_length=9)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
