# Generated by Django 4.0.5 on 2022-08-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
