# Generated by Django 4.0.5 on 2022-08-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_full_name_alter_appointment_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='host',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='password',
        ),
        migrations.AlterField(
            model_name='artist',
            name='mobile',
            field=models.CharField(max_length=9),
        ),
    ]
