# Generated by Django 4.0.5 on 2022-08-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
