# Generated by Django 4.0.5 on 2022-08-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_artist_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(unique=True),
        ),
    ]
