# Generated by Django 4.0.5 on 2022-08-26 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='user',
            new_name='creater',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 1, 27, 10, 330847)),
        ),
    ]
