# Generated by Django 4.0.5 on 2022-08-26 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_user_artist_creater_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
