# Generated by Django 4.0.5 on 2022-08-30 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_artist_profile_alter_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='artist',
            name='json',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
