# Generated by Django 4.0.5 on 2022-08-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_gettimes_remove_appointment_timestamp_artist_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gettimes',
            name='time',
        ),
    ]
