# Generated by Django 4.0.5 on 2022-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_gettimes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(max_length=100),
        ),
    ]
