# Generated by Django 4.0.5 on 2022-09-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_appointment_mobile_alter_appointment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
